############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456
  hikari:
    connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
    minimum-idle: 5                 # 最小连接数
    maximum-pool-size: 20           # 最大连接数
    auto-commit: true               # 自动提交
    idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP     # 连接池名字
    max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
    connection-test-query: SELECT 1
    ############################################################
    #
    # mybatis 配置
    #
    ############################################################
  servlet:
    multipart:
      max-file-size: 512000
      max-request-size: 512000

mybatis:
  type-aliases-package: com.example.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台在数据层打印MyBatis的Sql执行语句
mapper:
  mappers: com.example.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
custom:
  resourceLoctaion: /home/devsoft/tomcat/resources/   #静态资源映射目录